In [1]:
import pandas as pd
import numpy as np

In [2]:
libro='Libro1.csv'
df=pd.read_csv(libro)
df

nombre estado-civil    sexo nacionalidadedad  edad enfermedad
0     Antonio      soltero  hombre         espa�ola    45         no
1         Eva     separado   mujer       portuguesa    34         si
2        Juan       casado  hombre        irlandesa    32         no
3         Ana      soltero   mujer         espa�ola    37         si
4     Alfredo      soltero  hombre       portuguesa    46         no
5      Carmen       casado   mujer         francesa    51         no
6        Jose       casado  hombre         espa�ola    26         no
7       Juana       casado   mujer         francesa    28         no
8       Angel     separado  hombre       portuguesa    30         no
9      Amelia       casado   mujer       portuguesa    31         si
10     Isabel       casado   mujer         espa�ola    25         no
11     Carlos     separado  hombre         espa�ola    29         no
12      Maria       casado   mujer         espa�ola    33         no
13  Adoracion     separado   mujer         espa�ola    32         si
14     Javier       casado  hombre       portuguesa    56         no
15      Pedro     separado  hombre       portuguesa    54         no
16  Guadalupe       casado   mujer       portuguesa    24         no

In [4]:
df['nombre']=pd.Categorical(df['nombre'])
df['estado-civil']=pd.Categorical(df['estado-civil'])
df['sexo']=pd.Categorical(df['sexo'])
df['nacionalidadedad']=pd.Categorical(df['nacionalidadedad'])
df['enfermedad']=pd.Categorical(df['enfermedad'])

In [5]:
df['nombre']=df['nombre'].cat.codes
df['estado-civil']=df['estado-civil'].cat.codes
df['sexo']=df['sexo'].cat.codes
df['nacionalidadedad']=df['nacionalidadedad'].cat.codes
df['enfermedad']=df['enfermedad'].cat.codes

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   nombre            17 non-null     int8 
 1   estado-civil      17 non-null     int8 
 2   sexo              17 non-null     int8 
 3   nacionalidadedad  17 non-null     int8 
 4   edad              17 non-null     int64
 5   enfermedad        17 non-null     int8 
dtypes: int64(1), int8(5)
memory usage: 349.0 bytes


In [7]:
x=df.drop(['enfermedad'],axis=1)
y=df['enfermedad']


In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y, test_size=0.2,random_state=0)

#Regresión linear

In [10]:
from sklearn import linear_model

In [11]:
modelo=linear_model.LinearRegression()

In [12]:
from sklearn.model_selection import GridSearchCV

In [13]:
parameters={"n_jobs":[-1,0,1,2]}
grid= GridSearchCV(estimator=modelo,param_grid=parameters,cv=3)
grid.fit(X_train,Y_train)

GridSearchCV(cv=3, estimator=LinearRegression(),
             param_grid={'n_jobs': [-1, 0, 1, 2]})

In [15]:
X_test

nombre  estado-civil  sexo  nacionalidadedad  edad
1       8             1     1                 3    34
6      12             0     0                 0    26
8       4             1     0                 3    30
9       2             0     1                 3    31

In [16]:
Y_test_pred=grid.predict(X_test)

In [17]:
Y_test_pred

array([ 0.34090105, -0.22880094,  0.04909215,  0.29705092])

In [18]:
import sklearn.metrics as metrics

In [26]:
umbral=0.5
y_umbralizadas=1*(Y_test_pred[:]>umbral)
y_umbralizadas

array([0, 0, 0, 0])

In [27]:
print(u"Matriz de confusión\n",metrics.confusion_matrix(Y_test, y_umbralizadas))

Matriz de confusión
 [[2 0]
 [2 0]]


In [28]:
from sklearn.neighbors import  KNeighborsRegressor

In [29]:
model1=KNeighborsRegressor()
params={'n_neighbors': range(1,20)}
modelgs=GridSearchCV(model1,params,cv=3)

In [ ]:
modelgs.fit(X_train,Y_train)

In [31]:
Y_test_vecino=modelgs.predict(X_test)

In [32]:
Y_test_vecino

array([0., 0., 0., 1.])

In [33]:
umbral=0.5
y_umbralizadas2=1*(Y_test_vecino[:]>umbral)
y_umbralizadas

array([0, 0, 0, 0])

In [34]:
print(u"Matriz de confusión\n",metrics.confusion_matrix(Y_test, y_umbralizadas2))

Matriz de confusión
 [[2 0]
 [1 1]]
