---
---
---
---
# Aprendiendo a Programar Redes Neuronales
---
---
### Antonio Alvarez Gómez
---
---
---
---
2. Redes Neuronales 2 Antonio ipynb

  1. Ejemplo de Red Neuronal de puerta AND en Keras

  

---
---
#2.1 Red Neuronal de puerta AND en Keras
---
---


Una red neuronal es un modelo computacional inspirado en la forma en que funciona el cerebro humano. Consiste en una serie de capas de nodos interconectados, donde cada nodo recibe una entrada, realiza una operación matemática y produce una salida que se conecta a los nodos de la siguiente capa.

Keras es una biblioteca de Python de código abierto para la creación de redes neuronales. Proporciona una interfaz de alto nivel para definir, entrenar y evaluar modelos de redes neuronales de forma fácil y rápida.

La función básica de una red neuronal en Keras se define mediante el objeto Sequential. Por ejemplo, una red neuronal con una capa oculta y una neurona  se puede definir así:

In [1]:
#Importamos el objeto Sequential de Keras y la clase Dense de Keras
from keras.models import Sequential
from keras.layers import Dense
#Creamos el mdelo de red neuronal con una capa y una neurona, dos entradas y una salida
model = Sequential()
model.add(Dense(1, input_dim=2, activation='sigmoid'))


In [2]:
# Definimos  x_train
x_train = [
                [0,0],
                [0,1],
                [1,0],
                [1,1]
]
x=x_train;
# Definimos y_train
y_train = [
                [0],
                [0],
                [0],
                [1]
]


In [3]:
# como ves, las entradas de las listas estan ordenadas para que cuadren los 
# datos y las soluciones
print("Soluciones de una puerta logica AND:")
for i, d in enumerate(x_train):
    print("Para la entrada ", d, " la puerta da una salida de ", y_train[i])

Soluciones de una puerta logica AND:
Para la entrada  [0, 0]  la puerta da una salida de  [0]
Para la entrada  [0, 1]  la puerta da una salida de  [0]
Para la entrada  [1, 0]  la puerta da una salida de  [0]
Para la entrada  [1, 1]  la puerta da una salida de  [1]


---
---
Una función de pérdida es uno de los dos argumentos necesarios para compilar un modelo de Keras.

---
---

En el aprendizaje profundo, la pérdida se calcula para obtener los gradientes con respecto a los pesos del modelo y actualizar esos pesos en consecuencia a través de la retropropagación. Se calcula la pérdida y la red se actualiza después de cada iteración hasta que las actualizaciones del modelo no traigan ninguna mejora en la métrica de evaluación deseada. 

---
Optimizador
---

---
---
Métricas

---
---



In [4]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


model.fit(x_train, y_train, epochs=1000, batch_size=32)

Epoch 1/1000
1/1 [==============================] - 7s 7s/step - loss: 0.7969 - accuracy: 0.5000
Epoch 2/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.7963 - accuracy: 0.5000
Epoch 3/1000
1/1 [==============================] - 0s 23ms/step - loss: 0.7956 - accuracy: 0.5000
Epoch 4/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.7949 - accuracy: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.7943 - accuracy: 0.5000
Epoch 6/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.7936 - accuracy: 0.5000
Epoch 7/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.7930 - accuracy: 0.5000
Epoch 8/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.7923 - accuracy: 0.5000
Epoch 9/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.7917 - accuracy: 0.5000
Epoch 10/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.7910 - accuracy: 0.5000
Epoch 11/10

In [5]:
import numpy as np
# Transformaremos estas listas a listas de Numpy
x_train = np.array(x_train)
y_train = np.array(y_train)# 6)
# Por ultimo, ahora que nuestra red esta entrenada, vamos a probar a pasarle 
# datos a ver que es lo que nos saca. Para ello usaremos el modelo (la variable)
# como si fuera una funcion, pasandole por parametros una lista con los datos 
# que queremos que prediga

# Los datos sera nuestra lista de datos de entrada x_train
predicciones = model(x_train).numpy()

# Mostramos la salida de la red para cada uno de los datos
for i, p in enumerate(predicciones):
    print("Para la entrada ", x_train[i], " la red predice una salida de ", p)

# Banalizamos la salida de la red para cada uno de los datos
for i, p in enumerate(predicciones):
  if (p<0.5):
    print("Para la entrada ", x_train[i], " la red predice una salida de ", 0 ," i ",i)
else: print("Para la entrada ", x_train[i], " la red predice una salida de ", 1," i ",i)

Para la entrada  [0 0]  la red predice una salida de  [0.3110668]
Para la entrada  [0 1]  la red predice una salida de  [0.37665924]
Para la entrada  [1 0]  la red predice una salida de  [0.4581129]
Para la entrada  [1 1]  la red predice una salida de  [0.53082144]
Para la entrada  [0 0]  la red predice una salida de  0  i  0
Para la entrada  [0 1]  la red predice una salida de  0  i  1
Para la entrada  [1 0]  la red predice una salida de  0  i  2
Para la entrada  [1 1]  la red predice una salida de  1  i  3


In [6]:
# Guardar predicciones para futuras verificaciones
predictions = model.predict(x_train)


1/1 [==============================] - 0s 61ms/step


In [7]:
predictions

array([[0.3110668 ],
       [0.37665924],
       [0.4581129 ],
       [0.53082144]], dtype=float32)

In [8]:
xp=model.predict(x)

1/1 [==============================] - 0s 31ms/step


In [9]:
xp

array([[0.3110668 ],
       [0.37665924],
       [0.4581129 ],
       [0.53082144]], dtype=float32)

In [10]:
salis = model.predict([[0,0]])

1/1 [==============================] - 0s 31ms/step


In [11]:
salis

array([[0.3110668]], dtype=float32)

In [12]:
import keras

In [13]:
# Guardar el Modelo
model.save('path_to_my_model.h5')

# Recrea exactamente el mismo modelo solo desde el archivo
new_model = keras.models.load_model('path_to_my_model.h5')


---
---
La misma red neuronal cambiando parámetros

---
---

In [14]:
model.compile(loss='mean_squared_error', optimizer='sgd', metrics=['binary_accuracy'])


model.fit(x_train, y_train, epochs=1000, batch_size=32)

Epoch 1/1000
1/1 [==============================] - 0s 395ms/step - loss: 0.1672 - binary_accuracy: 1.0000
Epoch 2/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.1671 - binary_accuracy: 1.0000
Epoch 3/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.1670 - binary_accuracy: 1.0000
Epoch 4/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.1670 - binary_accuracy: 1.0000
Epoch 5/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.1669 - binary_accuracy: 1.0000
Epoch 6/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.1669 - binary_accuracy: 1.0000
Epoch 7/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.1668 - binary_accuracy: 1.0000
Epoch 8/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.1667 - binary_accuracy: 1.0000
Epoch 9/1000
1/1 [==============================] - 0s 19ms/step - loss: 0.1667 - binary_accuracy: 1.0000
Epoch 10/1000
1/1 [=============================