# Redes Neuronales Recurrentes RNN 1 1

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
%matplotlib inline
plt.rcParams['figure.figsize'] = (16, 9)
plt.style.use('fast')

from keras.models import Sequential
from keras.layers import Dense,Activation,Flatten
from sklearn.preprocessing import MinMaxScaler
fich='Temporal.csv'
aa18=pd.read_csv(fich)

In [ ]:

aa18

Reg  Valor
0       1    541
1       3    463
2       5    394
3       7    224
4       9    578
..    ...    ...
596  1193    394
597  1195    130
598  1197    603
599  1199    130
600  1201    527

[601 rows x 2 columns]

In [ ]:
aa18.shape

(601, 2)

In [ ]:
X = aa18.drop('Valor', axis=1)
Y = aa18['Valor']

In [ ]:
X

Reg
0       1
1       3
2       5
3       7
4       9
..    ...
596  1193
597  1195
598  1197
599  1199
600  1201

[601 rows x 1 columns]

In [ ]:
Y

0      541
1      463
2      394
3      224
4      578
      ... 
596    394
597    130
598    603
599    130
600    527
Name: Valor, Length: 601, dtype: int64

In [ ]:

from sklearn.preprocessing import StandardScaler

In [ ]:
# Normalizamos variables
scaler = StandardScaler()
XY = scaler.fit_transform(X)

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(XY, Y, test_size=0.2, random_state=0)

#NN en keras

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

# Crear modelo NN
model = Sequential()
model.add(Dense(units=1, activation='relu', input_dim=1))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))

# Compilar el modelo
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Entrenar el modelo
model.fit(X_train, Y_train, epochs=10, batch_size=32)


Epoch 1/10
15/15 [==============================] - 1s 4ms/step - loss: -33.2129 - accuracy: 0.0042 
Epoch 2/10
15/15 [==============================] - 0s 3ms/step - loss: -61.2151 - accuracy: 0.0042
Epoch 3/10
15/15 [==============================] - 0s 3ms/step - loss: -92.1859 - accuracy: 0.0042
Epoch 4/10
15/15 [==============================] - 0s 4ms/step - loss: -125.8922 - accuracy: 0.0042
Epoch 5/10
15/15 [==============================] - 0s 5ms/step - loss: -164.5894 - accuracy: 0.0042
Epoch 6/10
15/15 [==============================] - 0s 3ms/step - loss: -207.2422 - accuracy: 0.0042
Epoch 7/10
15/15 [==============================] - 0s 3ms/step - loss: -255.7999 - accuracy: 0.0042
Epoch 8/10
15/15 [==============================] - 0s 3ms/step - loss: -310.2183 - accuracy: 0.0042
Epoch 9/10
15/15 [==============================] - 0s 3ms/step - loss: -370.8080 - accuracy: 0.0042
Epoch 10/10
15/15 [==============================] - 0s 3ms/step - loss: -438.3593 - accuracy

In [ ]:
aa=model.predict([[1.4]])

1/1 [==============================] - 0s 162ms/step


In [ ]:
aa

array([[0.69483685]], dtype=float32)

In [ ]:
#Importamos el objeto Sequential de Keras y la clase Dense de Keras
from keras.models import Sequential
from keras.layers import Dense
#Creamos el mdelo de red neuronal con una capa y una neurona, una entrada y una salida
model2 = Sequential()
model2.add(Dense(1, input_dim=1, activation='softmax'))


In [ ]:
model2.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


model2.fit(X_train, Y_train, epochs=10, batch_size=32)

Epoch 1/10
15/15 [==============================] - 1s 2ms/step - loss: -0.9009 - accuracy: 0.0042
Epoch 2/10
15/15 [==============================] - 0s 2ms/step - loss: -5.5220 - accuracy: 0.0042
Epoch 3/10
15/15 [==============================] - 0s 2ms/step - loss: -10.2101 - accuracy: 0.0042
Epoch 4/10
15/15 [==============================] - 0s 2ms/step - loss: -14.7837 - accuracy: 0.0042
Epoch 5/10
15/15 [==============================] - 0s 2ms/step - loss: -19.4371 - accuracy: 0.0042
Epoch 6/10
15/15 [==============================] - 0s 2ms/step - loss: -24.0453 - accuracy: 0.0042
Epoch 7/10
15/15 [==============================] - 0s 2ms/step - loss: -28.7225 - accuracy: 0.0042
Epoch 8/10
15/15 [==============================] - 0s 2ms/step - loss: -33.2676 - accuracy: 0.0042
Epoch 9/10
15/15 [==============================] - 0s 2ms/step - loss: -37.9176 - accuracy: 0.0042
Epoch 10/10
15/15 [==============================] - 0s 2ms/step - loss: -42.5485 - accuracy: 0.0042


In [ ]:
aa2=model2.predict([[1.4]])

1/1 [==============================] - 0s 64ms/step


In [ ]:
aa2

array([[1.]], dtype=float32)

#RNN en keras

In [ ]:
from keras.models import Sequential
from keras.layers import SimpleRNN, Dense

# Crear modelo RNN
model1 = Sequential()
model1.add(SimpleRNN(units=1, activation='relu', input_shape=(10, 1)))
model1.add(Dense(units=32, activation='relu'))
model1.add(Dense(units=1, activation='sigmoid'))

# Compilar el modelo
model1.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Entrenar el modelo
model1.fit(X_train, Y_train, epochs=10, batch_size=32)


Epoch 1/10
15/15 [==============================] - 1s 3ms/step - loss: -24.8965 - accuracy: 0.0042 
Epoch 2/10
15/15 [==============================] - 0s 3ms/step - loss: -52.5513 - accuracy: 0.0042
Epoch 3/10
15/15 [==============================] - 0s 2ms/step - loss: -82.1630 - accuracy: 0.0042
Epoch 4/10
15/15 [==============================] - 0s 2ms/step - loss: -115.0314 - accuracy: 0.0042
Epoch 5/10
15/15 [==============================] - 0s 2ms/step - loss: -151.7531 - accuracy: 0.0042
Epoch 6/10
15/15 [==============================] - 0s 2ms/step - loss: -194.1926 - accuracy: 0.0042
Epoch 7/10
15/15 [==============================] - 0s 2ms/step - loss: -241.3487 - accuracy: 0.0042
Epoch 8/10
15/15 [==============================] - 0s 2ms/step - loss: -295.7698 - accuracy: 0.0042
Epoch 9/10
15/15 [==============================] - 0s 2ms/step - loss: -356.8506 - accuracy: 0.0042
Epoch 10/10
15/15 [==============================] - 0s 2ms/step - loss: -425.3861 - accuracy

In [ ]:
aa1=model1.predict([[1.4]])

1/1 [==============================] - 0s 186ms/step


In [ ]:
aa1

array([[0.6989866]], dtype=float32)

In [ ]:

from keras.layers import Dense, SimpleRNN



In [ ]:
model3 = Sequential()
model3.add(SimpleRNN(1, input_shape=(1, 1), return_sequences=True))
model3.add(Dense(1, activation="linear"))

In [ ]:
model3.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


model3.fit(X_train, Y_train, epochs=10, batch_size=32)

Epoch 1/10
15/15 [==============================] - 1s 2ms/step - loss: 701.8937 - accuracy: 0.0021  
Epoch 2/10
15/15 [==============================] - 0s 2ms/step - loss: 656.2523 - accuracy: 0.0021 
Epoch 3/10
15/15 [==============================] - 0s 2ms/step - loss: 624.5853 - accuracy: 0.0021
Epoch 4/10
15/15 [==============================] - 0s 2ms/step - loss: 607.2677 - accuracy: 0.0021 
Epoch 5/10
15/15 [==============================] - 0s 2ms/step - loss: 602.5050 - accuracy: 0.0021
Epoch 6/10
15/15 [==============================] - 0s 2ms/step - loss: 584.9724 - accuracy: 0.0021 
Epoch 7/10
15/15 [==============================] - 0s 2ms/step - loss: 537.9314 - accuracy: 0.0021 
Epoch 8/10
15/15 [==============================] - 0s 2ms/step - loss: 504.2604 - accuracy: 0.0021 
Epoch 9/10
15/15 [==============================] - 0s 2ms/step - loss: 498.1217 - accuracy: 0.0021
Epoch 10/10
15/15 [==============================] - 0s 2ms/step - loss: 493.8234 - accuracy:

In [ ]:
aa3=model3.predict([[1.4]])

1/1 [==============================] - 0s 201ms/step


In [ ]:
aa3

array([[[1.5535202]]], dtype=float32)